-- return {
-- 	"akinsho/toggleterm.nvim",
-- 	version = "*",
-- 	opts = {
-- 		size = 15,
-- 		open_mapping = [[<C-\>]], -- toggle avec Ctrl + \
-- 		autochdir = true,
-- 		shade_terminals = true,
-- 		start_in_insert = true,
-- 		insert_mappings = true,
-- 		terminal_mappings = true,
-- 		persist_size = true,
-- 		persist_mode = true,
-- 		direction = "horizontal", -- "vertical" | "float" | "tab"
-- 		close_on_exit = true,
-- 		shell = vim.o.shell, -- ton shell (bash, zsh, fish, etc.)
-- 	},
-- }
